### ISSUE TITLE
[Question] Video/ Custom data loading

### ISSUE THREAD

**Issue by vakkov** [DeanChan/HOIM-PyTorch#1]
Hi! Thank you so much for the nicely written paper and clean implementation!
I was wondering if there is a way to load a few frames without having any pre-existing gallery with its corresponding targets that contain the box coordinates and labels. Would the network be able to cut the people out of said frames and eventually re-identify them a few frames later?

**Comment by dichen-cd** [comment]
I'm not sure what your question means. Do you mean you want to find a specific probe person appearing in the first frame among the later frames? If so, you just detect and extract embeddings for all persons within the later frames using [these codes](https://github.com/DeanChan/HOIM-PyTorch/blob/3627cda688517564469ee0c14ee4c3bb155be130/lib/utils/evaluator.py#L16-L27) by changing the gallery loader. Then extract the embedding for the probe person using [these codes](https://github.com/DeanChan/HOIM-PyTorch/blob/3627cda688517564469ee0c14ee4c3bb155be130/lib/utils/evaluator.py#L32) and calculate the cosine similarity between probe embedding and detected embeddings.
