### ISSUE TITLE
requirements file

### ISSUE THREAD

**Issue by Alexadlu** [DeanChan/HOIM-PyTorch#2]
There may be something wrong with this file. I can't install most of the libraries in the file.
I tried to install in multiple versions of conda, and they all had the same error.
So I would like to ask how to use this file and whether it is the wrong document?

**Comment by dichen-cd** [comment]
Could you provide the error message? I have tested the requirements and I don't see any error message.

**Comment by Alexadlu** [comment]
(base) luandong@amax:~/code/Phd_work/HOIM_code/HOIM-PyTorch$ conda create --name HOIM --file requirements.txt
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - apex==0.1=pypi_0
  - ipykernel==4.10.0=pypi_0
  - testpath==0.4.2=pypi_0
  - motmetrics==1.1.3=pypi_0
  - scikit-learn==0.20.4=pypi_0
  - torchvision==0.4.0=pypi_0
  - entrypoints==0.3=pypi_0
  - pandocfilters==1.4.2=pypi_0
  - jupyter-core==4.5.0=pypi_0
  - pytorch==1.2.0=py2.7_cuda10.0.130_cudnn7.6.2_0
  - scandir==1.10.0=pypi_0
  - markdown==3.1.1=pypi_0
  - widgetsnbextension==3.5.1=pypi_0
  - contextlib2==0.6.0.post1=pypi_0
  - werkzeug==0.15.5=pypi_0
  - pytest==4.6.7=pypi_0
  - typing==3.7.4.1=pypi_0
  - inotify==0.2.10=pypi_0
  - pexpect==4.7.0=pypi_0
  - webencodings==0.5.1=pypi_0
  - terminado==0.8.2=pypi_0
  - h5py==2.10.0=pypi_0
  - backports-abc==0.5=pypi_0
  - ipdb==0.12.2=pypi_0
  - mistune==0.8.4=pypi_0
  - pluggy==0.13.1=pypi_0
  - tornado==5.1.1=pypi_0
  - protobuf==3.9.0=pypi_0
  - python-dateutil==2.8.0=pypi_0
  - send2trash==1.5.0=pypi_0
  - nose==1.3.7=pypi_0
  - prompt-toolkit==1.0.16=pypi_0
  - ipython==5.8.0=pypi_0
  - defusedxml==0.6.0=pypi_0
  - bleach==3.1.0=pypi_0
  - configparser==3.7.4=pypi_0
  - packaging==19.2=pypi_0
  - wcwidth==0.1.7=pypi_0
  - cuda100==1.0=0
  - pygments==2.4.2=pypi_0
  - jupyter==1.0.0=pypi_0
  - openpyxl==2.6.4=pypi_0
  - prometheus-client==0.7.1=pypi_0
  - jupyter-console==5.2.0=pypi_0
  - et-xmlfile==1.0.1=pypi_0
  - scipy==1.2.2=pypi_0
  - markupsafe==1.1.1=pypi_0
  - sklearn==0.0=pypi_0
  - pickleshare==0.7.5=pypi_0
  - nbconvert==5.5.0=pypi_0
  - functools32==3.2.3.post2=pypi_0
  - grpcio==1.22.0=pypi_0
  - singledispatch==3.4.0.3=pypi_0
  - more-itertools==5.0.0=pypi_0
  - ptyprocess==0.6.0=pypi_0
  - lapsolver==1.0.2=dev_0
  - nbformat==4.4.0=pypi_0
  - metric-learn==0.5.0=pypi_0
  - traitlets==4.3.2=pypi_0
  - pyzmq==18.0.2=pypi_0
  - pyrsistent==0.15.4=pypi_0
  - certifi==2019.6.16=pypi_0
  - zipp==0.6.0=pypi_0
  - ipywidgets==7.5.1=pypi_0
  - cython==0.29.14=pypi_0
  - jdcal==1.4.1=pypi_0
  - enum34==1.1.6=pypi_0
  - ipython-genutils==0.2.0=pypi_0
  - ipaddress==1.0.22=pypi_0
  - huepy==0.9.8.1=pypi_0
  - absl-py==0.7.1=pypi_0
  - cython-bbox==0.1.3=pypi_0
  - py==1.8.0=pypi_0
  - decorator==4.4.0=pypi_0
  - atomicwrites==1.3.0=pypi_0
  - backports-shutil-get-terminal-size==1.0.0=pypi_0
  - pandas==0.24.2=pypi_0
  - simplegeneric==0.8.1=pypi_0
  - pytorch-ignite==0.2.0=pypi_0
  - jsonschema==3.0.1=pypi_0
  - qtconsole==4.5.2=pypi_0
  - jinja2==2.10.1=pypi_0
  - notebook==5.7.8=pypi_0
  - tb-nightly==1.15.0a20190731=pypi_0
  - tqdm==4.32.2=pypi_0
  - attrs==19.1.0=pypi_0
  - pathlib2==2.3.4=pypi_0
  - jupyter-client==5.3.1=pypi_0
  - importlib-metadata==1.3.0=pypi_0

Current channels:

  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
  - https://conda.anaconda.org/genomedk/linux-64
  - https://conda.anaconda.org/genomedk/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
 

请问你用的是anconda2安装的吗？我这边没法直接使用你提供的命令，会出现上述错误。。

**Comment by dichen-cd** [comment]
Yes I am using anaconda2.
That's wired. Conda should sort out the way to install these packages automatically.
Maybe you could try:
1. Add [https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud](https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud) to your channel
2. Install `pytorch==1.2.0=py2.7_cuda10.0.130_cudnn7.6.2_0` and `cuda100==1.0=0` with conda from the channel added in the first step
3. Install the rest of the packages with `pip` .

**Comment by Alexadlu** [comment]
好的谢谢，我之前都是使用的anconda3安装的，我明天使用一下anconda2试试
想必您这个工作应该酝酿蛮久的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DeanChan/HOIM-PyTorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月12日(星期天) 晚上10:40
收件人:&nbsp;"DeanChan/HOIM-PyTorch"<HOIM-PyTorch@noreply.github.com&gt;;
抄送:&nbsp;"今日"<1214670665@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DeanChan/HOIM-PyTorch] requirements file (#2)





 
Yes I am using anaconda2.
 That's wired. Conda should sort out the way to install these packages automatically.
 Maybe you could try:
  
Add https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud to your channel
 
Install pytorch==1.2.0=py2.7_cuda10.0.130_cudnn7.6.2_0 and cuda100==1.0=0 with conda from the channel added in the first step
 
Install the rest of the packages with pip .

**Comment by Alexadlu** [comment]
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
这个似乎已经被禁了 我无法使用了


(base) luandong@amax:~/code/Phd_work/HOIM_code/HOIM-PyTorch$ conda create --name HOIM --file requirements.txt
Collecting package metadata (repodata.json): failed


UnavailableInvalidChannel: The channel is not accessible or is invalid.
&nbsp; channel name: anaconda/cloud
&nbsp; channel url: https://mirrors.ustc.edu.cn/anaconda/cloud
&nbsp; error code: 404


You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.



是否还有其他的解决办法
2是指手动安装 pytorch=1.2.0 和 python2.7 以及cuda10.0.130和cudnn7.6.2_0这个些包吗？
后面的cuda100=1.0=0是指什么，不太理解，希望您可以稍微解释一下
谢谢
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DeanChan/HOIM-PyTorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月12日(星期天) 晚上10:40
收件人:&nbsp;"DeanChan/HOIM-PyTorch"<HOIM-PyTorch@noreply.github.com&gt;;
抄送:&nbsp;"今日"<1214670665@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DeanChan/HOIM-PyTorch] requirements file (#2)





 
Yes I am using anaconda2.
 That's wired. Conda should sort out the way to install these packages automatically.
 Maybe you could try:
  
Add https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud to your channel
 
Install pytorch==1.2.0=py2.7_cuda10.0.130_cudnn7.6.2_0 and cuda100==1.0=0 with conda from the channel added in the first step
 
Install the rest of the packages with pip .

**Comment by dichen-cd** [comment]
Click [https://mirrors.tuna.tsinghua.edu.cn/help/anaconda/](https://mirrors.tuna.tsinghua.edu.cn/help/anaconda/) this link and see the instructions on that page, not adding https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud directly as the channel.

**Comment by Alexadlu** [comment]
通过一个个pip安装完了，可以进行测试，并且精度也是和论文中的保持了一致，但是再准备训练时发现了这样一个问题，
(HOIM) adlu@amax:~/PHD_work/PS_code/PS_20HOIM/HOIM-PyTorch-master$ CUDA_VISIBLE_DEVICES=3 python2 scripts/train_hoim.py --debug --lr_warm_up -p ./logs/adlu_train/ --batch_size 5 --nw 5 --w_RCNN_loss_bbox 10.0 --epochs 22 --lr 0.003
Traceback (most recent call last):
  File "scripts/train_hoim.py", line 20, in <module>
    from lib.utils.trainer import get_trainer
  File "./lib/utils/trainer.py", line 3, in <module>
    from apex import amp
  File "/home/adlu/anaconda2/envs/HOIM/lib/python2.7/site-packages/apex/__init__.py", line 8, in <module>
    from . import amp
  File "/home/adlu/anaconda2/envs/HOIM/lib/python2.7/site-packages/apex/amp/__init__.py", line 1, in <module>
    from .amp import init, half_function, float_function, promote_function,\
  File "/home/adlu/anaconda2/envs/HOIM/lib/python2.7/site-packages/apex/amp/amp.py", line 1, in <module>
    from . import compat, rnn_compat, utils, wrap
  File "/home/adlu/anaconda2/envs/HOIM/lib/python2.7/site-packages/apex/amp/rnn_compat.py", line 1, in <module>
    from . import utils, wrap
  File "/home/adlu/anaconda2/envs/HOIM/lib/python2.7/site-packages/apex/amp/wrap.py", line 4, in <module>
    from . import rnn_compat
ImportError: cannot import name rnn_compat

经查 有两个原因，一个是gcc版本的问题，但是我查看了我的gcc版本和cuda是满足对应的（gcc5.4，cuda10.0+）
第二个是说要使用python3进行执行，难道这个算法的python版本不是python2.7嘛，想问一下这个算法训练时有什么特殊的地方嘛？
改成python3进行训练确实可以跳过上述的错误，但是出现了python2和python3之间的语句不兼容问题。

**Comment by dichen-cd** [comment]
It's an apex-related problem. Currently the reported results are not from training using apex, so you could delete all apex-related code safely.
The official repo of apex only support python 3. If you'd like to try I have a [python 2 fork](https://github.com/DeanChan/apex). It works in this project but I don't intend to update it anymore.
