### ISSUE TITLE
FPN problem

### ISSUE THREAD

**Issue by JunnHan** [DeanChan/HOIM-PyTorch#4]
Have you ever tried to add FPN structure into your network?

**Comment by dichen-cd** [comment]
Sorry I haven't tried.
If you'd like to try, I guess it should be pretty simple to modify the code with reference to [this script](https://github.com/pytorch/vision/blob/master/torchvision/models/detection/faster_rcnn.py).

**Comment by JunnHan** [comment]
Thx
