### ISSUE TITLE
OIM LOSS

### ISSUE THREAD

**Issue by Bigboy-Code** [DeanChan/HOIM-PyTorch#5]
I am very fortunate to read your paper.

I would like to know how to use OIM loss to train the network？

Thank you for your answer.

**Comment by Bigboy-Code** [comment]
I am very fortunate to read your paper. 

I would like to know how to use OIM loss to train the network？

Thank you for your answer.

**Comment by dichen-cd** [comment]
See https://github.com/DeanChan/NAE4PS/blob/master/lib/loss/oim.py .

**Comment by Bigboy-Code** [comment]
Thank you for your answer.
